### ISSUE TITLE
will use some of this

### ISSUE THREAD

**Issue by floswald** [advanced-js/syllabus#64]
Hi @afeld,

just got into here via the github education page. I'm designing a course in computational economics at Sciences Po Paris, and want to use github heavily. I will build on some of the things I'm seeing here. I will of course attribute that to you. I love the first lesson with the PR to register ones name! Maybe I can ping you nearer the time to find out how I'm supposed to run the `add_students.rb` script? 
Anyway, thanks a ton for sharing this.

Florian

**Comment by afeld** [comment]
That's fantastic! I'm flattered – glad it was helpful. Looking forward to seeing how you adapt it!

Going to close this issue, but feel free to follow up with questions.

> I love the first lesson with the PR to register ones name!

Thanks! I've used that in [multiple](https://pages.18f.gov/hourofcode/) [contexts](http://hackerhours.org/oss-workshop.html) and it's been very effective.
