### ISSUE TITLE
Why haven't you used GitHub Classroom for assignments?

### ISSUE THREAD

**Issue by ceefour** [advanced-js/syllabus#71]
Thank you Prof. @afeld for sharing your course and its structure in a very easy-to-read, very easy-to-reuse form (you even took time and effort to write the "meta").

I'm planning to fork it for our next course https://struktur-data.github.io/syllabus/

Anyway I'm curious why you haven't use GitHub Classroom for the assignments? I'm aware that probably at that time GitHub Classrom wasn't even born yet or in immature stage. So for today, would you recommend using GitHub Classrom or whether you're aware of any pitfalls/difficulties etc. regarding GitHub Classroom usage (or non-usage)?

Thank you 👍

**Comment by afeld** [comment]
So sorry for the slow response - glad to hear the materials were helpful! You're correct in that this course predated Classroom. I haven't used it so couldn't really say, but forking has worked fine for me in this class and others. Happy to answer any other questions!
